# Build workflow for portable apps
name: build-package

on:
  push:
    branches: 
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build-package:
    runs-on: windows-latest
    steps:
    - name: Checkout PortableApps.comInstaller
      uses: actions/checkout@v2
      with: 
        repository: uroesch/PortableApps.comInstaller
        path: PortableApps.comInstaller
        ref: master
        lfs: true
    - name: Checkout PortableApps.comLauncher
      uses: actions/checkout@v2
      with: 
        repository: uroesch/PortableApps.comLauncher
        path: PortableApps.comLauncher
        ref: patched
        lfs: true
    - name: Checkout WinMergeJPPortable
      uses: actions/checkout@v2
      with:
        path: WinMergeJPPortable
    - name: Run Update.ps1
      run: WinMergeJPPortable/Other/Update/Update.ps1
